// Lista de atividades secundárias padrão
export const ATIVIDADES_SECUNDARIAS_LIST = [
  { codigo: '4713000', descricao: 'Comércio varejista de alimentos variados' },
  { codigo: '4711302', descricao: 'Comércio de supermercados' },
  { codigo: '4722000', descricao: 'Comércio varejista de bebidas e cigarros' },
  { codigo: '4752001', descricao: 'Comércio varejista de vestuário' },
  { codigo: '4755100', descricao: 'Comércio varejista de eletrodomésticos' },
  { codigo: '4761201', descricao: 'Comércio varejista de livros' },
  { codigo: '4763001', descricao: 'Comércio varejista de cosméticos e perfumaria' },
  { codigo: '4764001', descricao: 'Comércio varejista de flores e plantas' },
  { codigo: '4772001', descricao: 'Comércio varejista de artigos de esporte' },
  { codigo: '4782001', descricao: 'Comércio varejista de joias e relógios' },
  { codigo: '5611202', descricao: 'Restaurante com serviço à la carte' },
  { codigo: '5611203', descricao: 'Restaurante com auto-serviço' },
  { codigo: '5612100', descricao: 'Serviços de catering e bufê' },
  { codigo: '6201500', descricao: 'Desenvolvimento de software sob encomenda' },
  { codigo: '6202100', descricao: 'Consultoria em tecnologia da informação' },
  { codigo: '6204000', descricao: 'Consultoria em gestão empresarial' },
  { codigo: '7210200', descricao: 'Pesquisa em engenharia e tecnologias' },
  { codigo: '4724100', descricao: 'Comércio varejista de carnes - açougue' },
  { codigo: '4724200', descricao: 'Comércio varejista de pescados' },
  { codigo: '4642100', descricao: 'Comércio varejista de materiais de construção' },
  { codigo: '4754100', descricao: 'Comércio varejista de combustíveis' },
  { codigo: '4757003', descricao: 'Comércio varejista de móveis' },
  { codigo: '4761300', descricao: 'Comércio varejista de discos e DVDs' },
  { codigo: '4773003', descricao: 'Comércio varejista de brinquedos' },
  { codigo: '4774001', descricao: 'Comércio varejista de artigos de escritório' },
  { codigo: '4781400', descricao: 'Comércio varejista de artigos de óptica' },
  { codigo: '1011100', descricao: 'Abate de reses' },
  { codigo: '1011200', descricao: 'Abate de aves' },
  { codigo: '1012100', descricao: 'Processamento de frutas' },
  { codigo: '1040100', descricao: 'Fabricação de bebidas não alcoólicas' },
  { codigo: '1071100', descricao: 'Fabricação de pão francês e bolo' },
];
