// Lista das principais atividades CNAE (Brazilian)
export const CNAE_LIST = [
  { codigo: '4711302', descricao: 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentares - supermercados' },
  { codigo: '4722000', descricao: 'Comércio varejista de bebidas e cigarros' },
  { codigo: '4644801', descricao: 'Comércio varejista de equipamentos de telefonia' },
  { codigo: '4613203', descricao: 'Intermediários de comércio de máquinas e equipamentos industriais' },
  { codigo: '6202100', descricao: 'Atividades de consultoria em tecnologia da informação' },
  { codigo: '6204000', descricao: 'Consultoria em gestão empresarial' },
  { codigo: '6203000', descricao: 'Consultoria em planejamento' },
  { codigo: '6201500', descricao: 'Atividades de desenvolvimento de software sob encomenda' },
  { codigo: '6201400', descricao: 'Consultoria em processamento de dados' },
  { codigo: '7210100', descricao: 'Pesquisa e desenvolvimento experimental em ciências físicas e naturais' },
  { codigo: '7210200', descricao: 'Pesquisa e desenvolvimento experimental em engenharia e tecnologias' },
  { codigo: '7220000', descricao: 'Pesquisa e desenvolvimento experimental em ciências sociais e humanas' },
  { codigo: '4721004', descricao: 'Comércio varejista de bebidas não alcoólicas' },
  { codigo: '4713000', descricao: 'Comércio varejista de alimentos variados sem predominância de hortifrutigranjeiros' },
  { codigo: '4721003', descricao: 'Comércio varejista de bebidas alcoólicas' },
  { codigo: '4726005', descricao: 'Comércio varejista de artigos de limpeza' },
  { codigo: '4642100', descricao: 'Comércio a varejo de materiais de construção em geral' },
  { codigo: '4721002', descricao: 'Comércio varejista de sucos e refrigerantes' },
  { codigo: '4753100', descricao: 'Comércio varejista de peças e acessórios para veículos automotores' },
  { codigo: '4662200', descricao: 'Comércio no atacado de equipamentos para escritório' },
  { codigo: '4647000', descricao: 'Comércio varejista de tintas, vernizes e materiais correlatos' },
  { codigo: '4690000', descricao: 'Comércio varejista de artigos usados' },
  { codigo: '4761400', descricao: 'Comércio varejista de medicamentos, produtos farmacêuticos e perfumaria' },
  { codigo: '5611202', descricao: 'Restaurante com serviço à la carte' },
  { codigo: '5611201', descricao: 'Restaurante com comida no balcão' },
  { codigo: '5611203', descricao: 'Restaurante com auto-serviço' },
  { codigo: '5611204', descricao: 'Restaurante especializado em rodízio' },
  { codigo: '5611299', descricao: 'Restaurante de outros tipos' },
  { codigo: '5612100', descricao: 'Serviços de catering, bufê e lanchonete' },
  { codigo: '5611205', descricao: 'Lanchonete' },
  { codigo: '4724100', descricao: 'Comércio varejista de carnes - açougue' },
  { codigo: '4724200', descricao: 'Comércio varejista de pescados' },
  { codigo: '4729099', descricao: 'Comércio varejista especializado em outros produtos de alimentação' },
  { codigo: '4671400', descricao: 'Comércio no atacado de produtos químicos' },
  { codigo: '4645101', descricao: 'Comércio varejista de ferragens e ferramentas' },
  { codigo: '4647101', descricao: 'Comércio varejista de tinta' },
  { codigo: '4741503', descricao: 'Comércio varejista de peças e acessórios para bicicletas' },
  { codigo: '4751101', descricao: 'Comércio varejista de tecidos' },
  { codigo: '4751102', descricao: 'Comércio varejista de artigos de cama, mesa e banho' },
  { codigo: '4752001', descricao: 'Comércio varejista de vestuário e acessórios' },
  { codigo: '4754100', descricao: 'Comércio varejista de combustíveis para veículos automotores' },
  { codigo: '4755100', descricao: 'Comércio varejista de eletrodomésticos e equipamentos de som e vídeo' },
  { codigo: '4756008', descricao: 'Comércio varejista de eletrodomésticos não especificados anteriormente' },
  { codigo: '4757003', descricao: 'Comércio varejista de móveis' },
  { codigo: '4757005', descricao: 'Comércio varejista de colchões' },
  { codigo: '4758001', descricao: 'Comércio varejista de artigos de iluminação' },
  { codigo: '4759001', descricao: 'Comércio varejista de móveis, artigos de iluminação e outros artigos de uso doméstico não especificados anteriormente' },
  { codigo: '4761201', descricao: 'Comércio varejista de livros' },
  { codigo: '4761202', descricao: 'Comércio varejista de jornais e revistas' },
  { codigo: '4761300', descricao: 'Comércio varejista de discos, DVDs e similares' },
  { codigo: '4762000', descricao: 'Comércio varejista de videogames, filmes e músicas, usados' },
  { codigo: '4763001', descricao: 'Comércio varejista de cosméticos, perfumaria e artigos de higiene pessoal' },
  { codigo: '4764001', descricao: 'Comércio varejista de flores e plantas' },
  { codigo: '4765004', descricao: 'Comércio varejista de produtos de vidro' },
  { codigo: '4771100', descricao: 'Comércio varejista de instrumentos musicais e acessórios' },
  { codigo: '4771200', descricao: 'Comércio varejista de artigos religiosos e roupas talares' },
  { codigo: '4772001', descricao: 'Comércio varejista de artigos de esporte' },
  { codigo: '4773003', descricao: 'Comércio varejista de brinquedos e artigos recreativos' },
  { codigo: '4774001', descricao: 'Comércio varejista de artigos de escritório' },
  { codigo: '4775001', descricao: 'Comércio varejista de peças e acessórios para máquinas e equipamentos para escritório' },
  { codigo: '4781400', descricao: 'Comércio varejista de artigos de óptica' },
  { codigo: '4782001', descricao: 'Comércio varejista de joias e relógios' },
  { codigo: '4784100', descricao: 'Comércio varejista de objetos de arte' },
  { codigo: '4784200', descricao: 'Comércio varejista de antiguidades' },
  { codigo: '4789099', descricao: 'Comércio varejista de outros artigos não especificados anteriormente' },
  { codigo: '4791100', descricao: 'Comércio varejista de vending machines (máquinas automáticas)' },
  { codigo: '4799008', descricao: 'Comércio varejista não especificado anteriormente' },
  { codigo: '1011100', descricao: 'Abate de reses' },
  { codigo: '1011200', descricao: 'Abate de aves' },
  { codigo: '1012100', descricao: 'Processamento, preservação e produção de suco de frutas' },
  { codigo: '1012200', descricao: 'Processamento e conservação de frutas' },
  { codigo: '1013100', descricao: 'Processamento e conservação de legumes' },
  { codigo: '1021400', descricao: 'Processamento, preservação e produção de suco de frutas cítricas' },
  { codigo: '1020100', descricao: 'Moagem, prensagem e torração de sementes oleaginosas' },
  { codigo: '1020200', descricao: 'Fabricação de alimentos para animais' },
  { codigo: '1030100', descricao: 'Fabricação de açúcar' },
  { codigo: '1040100', descricao: 'Fabricação de bebidas não alcoólicas' },
  { codigo: '1051100', descricao: 'Destilação de álcool' },
  { codigo: '1061100', descricao: 'Moagem de trigo' },
  { codigo: '1062100', descricao: 'Fabricação de produtos de moagem' },
  { codigo: '1063100', descricao: 'Fabricação de amidos e produtos derivados' },
  { codigo: '1071100', descricao: 'Fabricação de pão francês e bolo' },
  { codigo: '1071200', descricao: 'Fabricação de biscoitos e bolos' },
  { codigo: '1072100', descricao: 'Fabricação de macarrão' },
  { codigo: '1073100', descricao: 'Fabricação de chocolate e produtos de confeitaria' },
  { codigo: '1074100', descricao: 'Fabricação de café torrado em grão e moído' },
  { codigo: '1081100', descricao: 'Fabricação de açúcar cristal de cana-de-açúcar' },
  { codigo: '1091100', descricao: 'Fabricação de rações balanceadas para animais' },
  { codigo: '1092100', descricao: 'Fabricação de óleos e gorduras vegetais e animais' },
  { codigo: '1099099', descricao: 'Fabricação de outros alimentos não especificados' },
  { codigo: '1311800', descricao: 'Beneficiamento de sal marinho' },
  { codigo: '2011100', descricao: 'Extração de carvão mineral' },
  { codigo: '2412100', descricao: 'Petróleo bruto e gás natural' },
  { codigo: '2621001', descricao: 'Extração de quartzito e sílex' },
  { codigo: '2680000', descricao: 'Extração de pedras ornamentais, corte, acabamento e beneficiamento de rochas para uso na construção' },
  { codigo: '2710100', descricao: 'Refino de petróleo' },
];
